name: Lint and Format

on:
  push:
    branches:
      - '*'

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Lint code
        run: yarn lint

      - name: Format code
        run: yarn format
